Repository jvm-coder/Hacktoberfest2022_aakash, pull requests merged in 2022-10, with the labels that each got.

#21 Create Merge Sort java
  Merge Sort java
Labels: hacktoberfest-accepted

#20 Create Selection Sort java
  Selection Sort java
Labels: good first issue, hacktoberfest-accepted

#19 Create Insertion Sort java
  Insertion Sort java
Labels: hacktoberfest-accepted

#18 Create Bubble Sort java
  Bubble Sort java
Labels: hacktoberfest-accepted

#17 Single number
  Single number/Question.txt
  Single number/single.c
Labels: hacktoberfest-accepted

#22 I have added a bubble sort code for this file.
  bubbleSort.java
Labels: hacktoberfest-accepted

#23 Create ClosestToZero.java
  ClosestToZero.java
Labels: hacktoberfest-accepted

#24 Create PathSum.java
  PathSum.java
Labels: hacktoberfest-accepted

#25 Basic Patterns
  basicpatterns.java
Labels: hacktoberfest-accepted

#27 Added some java programs
  Enhanced.java
  Fibonacci.java
  NestedSwitch.java
  Reverse.java
  Switch.java
Labels: hacktoberfest-accepted

#28 permutation code java
  Java/Permutation.java
Labels: hacktoberfest-accepted

#29 Create ReverseLinkedList.java
  Java/ReverseLinkedList.java
Labels: hacktoberfest-accepted

#32 add java design patterns - singleton pattern
  Java/designPatterns/ThreadSafeSingleton.java
Labels: hacktoberfest-accepted

#31 eliminate duplicate nodes in linked list
  CONTRIBUTING.md
  CPP/eliminate duplicate nodes in linked list.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#30 Create reverse_array.c
  C/reverse_array.c
Labels: hacktoberfest-accepted

#33 Create sudoku.cpp
  CPP/sudoku.cpp
Labels: hacktoberfest-accepted

#34 add java design patterns - factory
  Java/designPatterns/factory/BMWCar.java
  Java/designPatterns/factory/Car.java
  Java/designPatterns/factory/CarFactory.java
Labels: hacktoberfest-accepted

#35 Make my laptop android apps
  Android Development/MyLaptopApps/.gitignore
  Android Development/MyLaptopApps/.idea/.gitignore
  Android Development/MyLaptopApps/.idea/.name
  Android Development/MyLaptopApps/.idea/compiler.xml
  Android Development/MyLaptopApps/.idea/gradle.xml
  Android Development/MyLaptopApps/.idea/misc.xml
  Android Development/MyLaptopApps/.idea/vcs.xml
  Android Development/MyLaptopApps/app/.gitignore
  Android Development/MyLaptopApps/app/build.gradle
  Android Development/MyLaptopApps/app/proguard-rules.pro
  Android Development/MyLaptopApps/app/src/androidTest/java/com/hacktoberfest/mylaptopapps/ExampleInstrumentedTest.kt
  Android Development/MyLaptopApps/app/src/main/AndroidManifest.xml
  Android Development/MyLaptopApps/app/src/main/java/com/hacktoberfest/mylaptopapps/MainActivity.kt
  Android Development/MyLaptopApps/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android Development/MyLaptopApps/app/src/main/res/drawable/ic_launcher_background.xml
  Android Development/MyLaptopApps/app/src/main/res/layout/activity_main.xml
  Android Development/MyLaptopApps/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android Development/MyLaptopApps/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android Development/MyLaptopApps/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android Development/MyLaptopApps/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Android Development/MyLaptopApps/app/src/main/res/values-night/themes.xml
  Android Development/MyLaptopApps/app/src/main/res/values/colors.xml
  Android Development/MyLaptopApps/app/src/main/res/values/strings.xml
  Android Development/MyLaptopApps/app/src/main/res/values/themes.xml
  Android Development/MyLaptopApps/app/src/main/res/xml/backup_rules.xml
  Android Development/MyLaptopApps/app/src/main/res/xml/data_extraction_rules.xml
  Android Development/MyLaptopApps/app/src/test/java/com/hacktoberfest/mylaptopapps/ExampleUnitTest.kt
  Android Development/MyLaptopApps/build.gradle
  Android Development/MyLaptopApps/gradle.properties
  Android Development/MyLaptopApps/gradle/wrapper/gradle-wrapper.jar
  Android Development/MyLaptopApps/gradle/wrapper/gradle-wrapper.properties
  Android Development/MyLaptopApps/gradlew
  Android Development/MyLaptopApps/gradlew.bat
  Android Development/MyLaptopApps/settings.gradle
Labels: hacktoberfest-accepted

#37 Create hashMap.java
  Java/hashMap.java
Labels: hacktoberfest-accepted

#38 Hactoberfest PR 2022
  CONTRIBUTING.md
  Python/FizzBuzz.py
Labels: hacktoberfest-accepted

#39 add python sort
  Python/sort.py
  Python/stack.py
Labels: hacktoberfest-accepted

#40 hacktoberfest-2022
  Java/QuickSort.java
Labels: hacktoberfest-accepted

#41 Update name in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#42 add python split
  Python/split.py
Labels: hacktoberfest-accepted

#43 Create convert km to miles.js
  convert km to miles.js
Labels: hacktoberfest-accepted

#45 New user contribution
  CONTRIBUTING.md
  Python/bubbleSort.py
Labels: hacktoberfest-accepted

#46 Create BinarySearch.java
  Java/BinarySearch.java
  JavaScript(JS)/.gitignore
  JavaScript(JS)/App.css
  JavaScript(JS)/App.js
  JavaScript(JS)/App.test.js
  JavaScript(JS)/README.md
  JavaScript(JS)/index.css
  JavaScript(JS)/index.js
  JavaScript(JS)/logo.svg
  JavaScript(JS)/package-lock.json
  JavaScript(JS)/package.json
  Web Development/about.php
  Web Development/contact.php
  Web Development/course.php
  Web Development/design.jpg
  Web Development/detail.php
  Web Development/feature.php
  Web Development/footer.php
  Web Development/index.php
  Web Development/navbar.php
  Web Development/team.php
  Web Development/testimonial.php
Labels: hacktoberfest-accepted

#47 Create Radix-Sort.cpp
  C/Radix-Sort.cpp
Labels: hacktoberfest-accepted

#48 Create floyydwarshal.cpp
  floyydwarshal.cpp
Labels: hacktoberfest-accepted

#49 Create Longest-Palindromic-Substring.py
  Python/Longest-Palindromic-Substring.py
Labels: hacktoberfest-accepted

#51 Create Kadanes_Algorithm.java
  Java/Kadanes_Algorithm.java
Labels: hacktoberfest-accepted

#52 Sorted the files in web development directory in particular folder.
  CONTRIBUTING.md
  Web Development/ed-tech website template/about.php
  Web Development/ed-tech website template/contact.php
  Web Development/ed-tech website template/course.php
  Web Development/ed-tech website template/design.jpg
  Web Development/ed-tech website template/detail.php
  Web Development/ed-tech website template/feature.php
  Web Development/ed-tech website template/footer.php
  Web Development/ed-tech website template/index.php
  Web Development/ed-tech website template/navbar.php
  Web Development/ed-tech website template/readme.md
  Web Development/ed-tech website template/team.php
  Web Development/ed-tech website template/testimonial.php
Labels: hacktoberfest-accepted

#54 Create lamda.java
  Java/lamda.java
Labels: hacktoberfest-accepted

#55 Create alphatriangle.c
  C/alphatriangle.c
Labels: hacktoberfest-accepted

#56 Create main.c
  C/main.c
Labels: hacktoberfest-accepted

#53 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#50 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#44 contribute to hacktoberfest 2022
  CONTRIBUTING.md
  Java/AlarmClock.java
Labels: hacktoberfest-accepted

#57 Create Min_Max_in_Array.java
  Java/Min_Max_in_Array.java
Labels: hacktoberfest-accepted

#58 Added Flappy Game Code In python script
  CONTRIBUTING.md
  Python/flappy.py
Labels: hacktoberfest-accepted

#59 Create RadixSort.java
  Java/RadixSort.java
Labels: hacktoberfest-accepted

#60 Added Infix to Postfix convertor using Stack in C++
  CONTRIBUTING.md
  CPP/Infix_To_Postfix.cpp
Labels: hacktoberfest-accepted

#61 Create BinarySearchTree.cpp
  CPP/BinarySearchTree.cpp
Labels: hacktoberfest-accepted

#62 Added Prime_Number in java language
  Java/Prime_Number.java
Labels: hacktoberfest-accepted

#63 add: copystr :rocket:
  CPP/copystr.cpp
Labels: hacktoberfest-accepted

#64 Create BinaryRecursiveSearch.cpp
  BinaryRecursiveSearch.cpp
  CPP/ClassLinkingStructures.cpp
  CPP/SinglyLinkedList.cpp
Labels: hacktoberfest-accepted

#65 Simple DevOps Project
  CONTRIBUTING.md
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/Dockerfile
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/README.md
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/pom.xml
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/pom.xml
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/src/main/java/com/example/Greeter.java
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/src/site/apt/index.apt
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/src/test/java/com/example/TestGreeter.java
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/target/classes/com/example/Greeter.class
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/target/maven-archiver/pom.properties
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/target/server.jar
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/target/surefire-reports/TEST-com.example.TestGreeter.xml
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/target/surefire-reports/com.example.TestGreeter.txt
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/server/target/test-classes/com/example/TestGreeter.class
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/pom.xml
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/src/main/webapp/WEB-INF/web.xml
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/src/main/webapp/index.jsp
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/target/maven-archiver/pom.properties
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/target/webapp.war
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/target/webapp/WEB-INF/web.xml
  DevOps/Simple DevOps Project/Build_and_deploy_on_tomcat/webapp/target/webapp/index.jsp
  DevOps/Simple DevOps Project/README.md
  DevOps/Simple DevOps Project/images/devops.jpg
Labels: hacktoberfest-accepted

#66 Create zigzagPattern.py
  Python/zigzagPattern.py
Labels: hacktoberfest-accepted

#67 Added Factorial.java
  Java/Factorial.java
Labels: hacktoberfest-accepted

#68 Added Heap Sort program in java language
  Java/Heap_Sort.java
Labels: hacktoberfest-accepted

#70 Applet awt Calcualtor in java
  CONTRIBUTING.md
  Java/CalculatorUsingApplet/CalculatorUsingAppletawt.java
Labels: hacktoberfest-accepted

#71 Create LinkedListCycle.java
  Java/LinkedListCycle.java
Labels: hacktoberfest-accepted

#72 Create LinkedListCycle.java
  Java/LinkedListCycle.java
Labels: hacktoberfest-accepted

#73 Encapsulation added
  Java/EncapsulationInJava/Encapsulation.jpg
  Java/EncapsulationInJava/main.java
Labels: hacktoberfest-accepted

#74 Deploy React App On Docker host
  DevOps/Deploy React App/.gitignore
  DevOps/Deploy React App/Dockerfile
  DevOps/Deploy React App/Images/CI-CD.jpg
  DevOps/Deploy React App/Images/ansible-server.PNG
  DevOps/Deploy React App/Images/deployedapp.PNG
  DevOps/Deploy React App/Images/dockerhost.PNG
  DevOps/Deploy React App/Images/dockerhub.PNG
  DevOps/Deploy React App/Images/jenkins.PNG
  DevOps/Deploy React App/README.md
  DevOps/Deploy React App/deploy_reactApp.yml
  DevOps/Deploy React App/package-lock.json
  DevOps/Deploy React App/package.json
  DevOps/Deploy React App/public/favicon.ico
  DevOps/Deploy React App/public/index.html
  DevOps/Deploy React App/public/logo192.png
  DevOps/Deploy React App/public/logo512.png
  DevOps/Deploy React App/public/manifest.json
  DevOps/Deploy React App/public/robots.txt
  DevOps/Deploy React App/reactApp.yml
  DevOps/Deploy React App/src/App.css
  DevOps/Deploy React App/src/App.js
  DevOps/Deploy React App/src/App.test.js
  DevOps/Deploy React App/src/index.css
  DevOps/Deploy React App/src/index.js
  DevOps/Deploy React App/src/logo.svg
  DevOps/Deploy React App/src/reportWebVitals.js
  DevOps/Deploy React App/src/setupTests.js
Labels: good first issue, hacktoberfest-accepted

#75 added primaryNumberChecker.php and myself to CONTRIBUTING.md
  CONTRIBUTING.md
  PHP/primaryNumberChecker.php
Labels: hacktoberfest-accepted

#76 Create Double Stack
  CPP/doubleStack.cpp
Labels: hacktoberfest-accepted

#77 Binary Search using recursion
  CPP/binary_Rec.cpp
  CPP/binary_Rec.exe
Labels: hacktoberfest-accepted

#78 Create Merge-Sort.cpp
  CPP/Merge-Sort.cpp
Labels: hacktoberfest-accepted

#80 Added 3 python files
  CONTRIBUTING.md
  Python/collatz_sequence.py
  Python/kaprekar_const.py
  Python/longest_common_prefix.py
Labels: good first issue, hacktoberfest-accepted

#82 adding simple guessing game
  CONTRIBUTING.md
  Python/guessingGame.py
Labels: hacktoberfest-accepted

#69 Applet awt Calculator added
  CONTRIBUTING.md
  Java/CalculatorUsingApplet/CalculatorUsingAppletawt.java
Labels: documentation

#84 Machine Learning Implementation Example
  CONTRIBUTING.md
  Machine learning/ImageClassification/README.md
  Machine learning/ImageClassification/assets/After.png
  Machine learning/ImageClassification/assets/Before.png
  Machine learning/ImageClassification/assets/sky.png
  Machine learning/ImageClassification/index.html
  Machine learning/ImageClassification/style.css
Labels: documentation

#87 javascript promises added
  CONTRIBUTING.md
  JavaScript(JS)/promiseExample.js
Labels: good first issue, hacktoberfest-accepted

#89 Added slicedvector
  CONTRIBUTING.md
  CPP/slicedvector.cpp
Labels: good first issue, hacktoberfest-accepted

#93 Create Counting-Sort.cpp
  CPP/Counting-Sort.cpp
Labels: documentation, hacktoberfest-accepted

#91 Peak element
  Java/peakArray.java
  Java/smallestGreatestElement.java
Labels: documentation, hacktoberfest-accepted

#90 smallest greatest element 2d array code
  Java/smallestGreatestElement.java
Labels: documentation

#86 Create HieghtOfTree.py
  Python/HieghtOfTree.py
Labels: documentation, good first issue, hacktoberfest-accepted

#85 Create QuickSort on Doubly Linked List.cpp
  CPP/QuickSort on Doubly Linked List.cpp
Labels: documentation, hacktoberfest-accepted

#83 Create Dijkstra’s Shortest Path Algorithm.cpp
  CPP/Dijkstra’s Shortest Path Algorithm.cpp
Labels: documentation, hacktoberfest-accepted

#94 hacktoberfest 2022
  PHP/function.php
Labels: good first issue, hacktoberfest-accepted

#95 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#96 Variety of pattern in C++
  CONTRIBUTING.md
  variety of Patterns in c++/pattern1.cpp
  variety of Patterns in c++/pattern1.exe
  variety of Patterns in c++/pattern2.cpp
  variety of Patterns in c++/pattern2.exe
  variety of Patterns in c++/pattern3.cpp
  variety of Patterns in c++/pattern3.exe
  variety of Patterns in c++/pattern4.cpp
  variety of Patterns in c++/pattern4.exe
  variety of Patterns in c++/pattern5.cpp
  variety of Patterns in c++/pattern5.exe
  variety of Patterns in c++/pattern6.cpp
  variety of Patterns in c++/pattern6.exe
Labels: hacktoberfest-accepted

#97 Cafe Landing Page
  Web Development/cafe-landing-page/images/1111.PNG
  Web Development/cafe-landing-page/images/222222.PNG
  Web Development/cafe-landing-page/images/cake1.PNG
  Web Development/cafe-landing-page/images/cake2.PNG
  Web Development/cafe-landing-page/images/deck1.PNG
  Web Development/cafe-landing-page/images/deck2.PNG
  Web Development/cafe-landing-page/images/deck3.PNG
  Web Development/cafe-landing-page/images/deck4.PNG
  Web Development/cafe-landing-page/images/final1.PNG
  Web Development/cafe-landing-page/images/final2.PNG
  Web Development/cafe-landing-page/images/final3.PNG
  Web Development/cafe-landing-page/images/final4.PNG
  Web Development/cafe-landing-page/images/final5.PNG
  Web Development/cafe-landing-page/images/final6.PNG
  Web Development/cafe-landing-page/images/first.PNG
  Web Development/cafe-landing-page/images/fuh.jfif
  Web Development/cafe-landing-page/images/logo.PNG
  Web Development/cafe-landing-page/images/logo1.PNG
  Web Development/cafe-landing-page/images/maining.jfif
  Web Development/cafe-landing-page/images/one.jfif
  Web Development/cafe-landing-page/images/soon.PNG
  Web Development/cafe-landing-page/images/yoo.PNG
  Web Development/cafe-landing-page/index.html
  Web Development/cafe-landing-page/style.css
Labels: good first issue, hacktoberfest-accepted

#100 face detection
  CONTRIBUTING.md
  Machine learning/Face detection/code.py
  Machine learning/Face detection/haarcascade_frontalface_default.xml
  Machine learning/Face detection/readme.md
Labels: hacktoberfest-accepted

#101 DFS
  Java/Dfs.java
Labels: good first issue, hacktoberfest-accepted

#102 Hacktoberfest-2022
  CONTRIBUTING.md
  PHP/17DesignCalc.php
Labels: hacktoberfest-accepted

#103 Add Bubblesort.php
  PHP/BubbleSort.php
Labels: hacktoberfest-accepted

#104 Reverse Array CPP
  CPP/reverse_array.cpp
Labels: hacktoberfest-accepted

#105 more sorting algo
  CPP/bubbleSort.cpp
  CPP/howSum.py
  CPP/insertionSort.cpp
  CPP/mergeSortInLinkedList.cpp
  CPP/quickSort.cpp
  CPP/selectionSort.cpp
Labels: good first issue, hacktoberfest-accepted

#109 Added a PHP Program to Count the No. of words in a Text File and listing the words separately in another Text File.(HTML File is also included)
  CONTRIBUTING.md
  PHP/WC.html
  PHP/WC.php
Labels: good first issue, hacktoberfest-accepted

#110 add linearSearch.cpp file
  CPP/linearSearch.cpp
Labels: good first issue, hacktoberfest-accepted

#111 chat application added
  Web Development/Chat_app/package-lock.json
  Web Development/Chat_app/package.json
  Web Development/Chat_app/public/chat.html
  Web Development/Chat_app/public/css/styles.css
  Web Development/Chat_app/public/css/styles.min.css
  Web Development/Chat_app/public/img/favicon.png
  Web Development/Chat_app/public/index.html
  Web Development/Chat_app/public/js/chat.js
  Web Development/Chat_app/src/index.js
  Web Development/Chat_app/src/utils/messages.js
  Web Development/Chat_app/src/utils/users.js
Labels: good first issue, hacktoberfest-accepted

#112 'color-detection'
  New folder/python-project-color-detection/color_detection.py
  New folder/python-project-color-detection/colorpic.jpg
  New folder/python-project-color-detection/colors.csv
Labels: hacktoberfest-accepted

#114 Added Commonly Asked DP Based Problems
  Java/CoinChange.java
  Java/FrequencyOfCharacters.java
  Java/LongestCommonSubsequence.java
  Java/OccuranceString.java
  Java/SubsetSum.java
Labels: hacktoberfest-accepted

#117 Added Image augmentation in Data Science folder
  Machine learning/Image Augmentation Methods/Image Augmentation in Python
  Machine learning/Image Augmentation Methods/Image1.jpg
Labels: hacktoberfest-accepted

#118 Add Key_logger in python
  Python/Key_logger.py
Labels: hacktoberfest-accepted

#127 Portscanner in python
  Portscanner.py
Labels: hacktoberfest-accepted

#123 Create removeAlphabets_Evaluate_exp.c
  C/removeAlphabets_Evaluate_exp.c
Labels: hacktoberfest-accepted

#124 Added my name to contributing.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#125 Added file to print rational numbers
  C/rat.c
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#126 Queue.py
  CONTRIBUTING.md
  Python/Queue.py
Labels: good first issue, hacktoberfest-accepted

#115 Added RotateList.java
  RotateList.java
Labels: hacktoberfest-accepted

#133 Added boolean
  boolean.py
Labels: hacktoberfest-accepted

#132 Create CNN.py
  Machine learning/ImageClassification/CNN.py
Labels: hacktoberfest-accepted

#134 added file
  CPP/find_LCM.cpp
Labels: hacktoberfest-accepted

#135 Added graph traversal algorithm to finad all paths in a grid
  Python/All Paths in Grids.py
Labels: good first issue, hacktoberfest-accepted

#136 Digit Recogniser
  Machine learning/Digit Recogniser/Digit Recogniser.ipynb
  Machine learning/Digit Recogniser/mnist submission.csv
Labels: hacktoberfest-accepted

#137 Roll Dice in python
  Python/RollDice.py
Labels: hacktoberfest-accepted

#139 Create cycRotate_arr_byOne.py
  Python/cycRotate_arr_byOne.py
Labels: hacktoberfest-accepted

#140 Create Negative_P_numbers.py
  Python/Negative_P_numbers.py
Labels: hacktoberfest-accepted

#141 Added ml Algorithms
  Machine learning/ML_algorithms/candidate.ipynb
  Machine learning/ML_algorithms/data1.csv
  Machine learning/ML_algorithms/findS.ipynb
Labels: hacktoberfest-accepted

#142 Added a simple calculator
  Python/calculator.py
Labels: hacktoberfest-accepted

#143 Added C++ program to convert binary tree to doubly linkedlist
  CONTRIBUTING.md
  CPP/binary tree to doubly linkedlist.cpp
Labels: hacktoberfest-accepted

#145 Added black jack game python script
  Python/Black_Jack_Game.py
Labels: hacktoberfest-accepted

#146 added details in contribution
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#144 G UI
  CONTRIBUTING.md
  GUI Project/Rock_Paper_Scissor.py
Labels: hacktoberfest-accepted

#147 Dab pr
  CONTRIBUTING.md
  Python/json_handling.py
Labels: hacktoberfest-accepted

#150 Create KadaneAlgorithm.php
  PHP/KadaneAlgorithm.php
Labels: hacktoberfest-accepted

#151 python added
  CONTRIBUTING.md
  Python/text-to-speech.py
Labels: hacktoberfest-accepted

#152 HandTracking Project(Hacktoberfest 2022)
  Python/HandTrack/HTrackMod.py
  Python/HandTrack/VolumeControl.py
  Python/HandTrack/__pycache__/HTrackMod.cpython-310.pyc
  Python/HandTrack/__pycache__/HTrackMod.cpython-39.pyc
  Python/HandTrack/base.py
Labels: hacktoberfest-accepted

#153 Added Permutations of string Problem using cpp
  CONTRIBUTING.md
  CPP/Permutation of string.cpp
Labels: hacktoberfest-accepted

#154 Added path sum BST problem's solution
  Python/pathsum_of_BST.py
Labels: hacktoberfest-accepted

#155 LeetCode Solution for an Problem on Reverse LinkedList -2
  CPP/206reverseLL.cpp
Labels: hacktoberfest-accepted

#157 Insertion Sort using recursion
  Insertion sort.py
Labels: hacktoberfest-accepted

#160 Added stack implementation code
  CPP/stack_implementation.cpp
Labels: hacktoberfest-accepted

#161 Add Springboot Application with MongoDB
  Java/SpringAppsWithMongoDB/.gitignore
  Java/SpringAppsWithMongoDB/.mvn/wrapper/maven-wrapper.jar
  Java/SpringAppsWithMongoDB/.mvn/wrapper/maven-wrapper.properties
  Java/SpringAppsWithMongoDB/mvnw
  Java/SpringAppsWithMongoDB/mvnw.cmd
  Java/SpringAppsWithMongoDB/pom.xml
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/LicenseServiceApplication.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/controller/LicenseController.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/dao/LicenseDao.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/dto/ResourceNotFoundException.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/dto/ResponseLicense.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/model/License.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/model/Status.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/repository/CustomLicenseRepository.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/repository/CustomLicenseRepositoryImpl.java
  Java/SpringAppsWithMongoDB/src/main/java/com/demo/license/service/repository/LicenseRepository.java
  Java/SpringAppsWithMongoDB/src/main/resources/application.properties
  Java/SpringAppsWithMongoDB/src/test/java/com/demo/license/service/LicenseDaoApplicationTests.java
Labels: hacktoberfest-accepted

#159 ColorDetection
  Python/deteksiwarna.py
Labels: hacktoberfest-accepted

#162 Added Insertion_sort in java language
  Java/Insertion_Sort.java
Labels: hacktoberfest-accepted

#163 Create heartmakingbypython.py
  Python/heartmakingbypython.py
Labels: hacktoberfest-accepted

#164 Added the DFS Program in CPP
  CPP/Depth_First_Search_using_recursion.cpp
  CPP/Stack_Operation_Using_Linked_List.cpp
Labels: hacktoberfest-accepted

#165 Create remove_duplicates.py
  Python/remove_duplicates.py
Labels: hacktoberfest-accepted

#172 Added a BMI calculator in JS for hacktoberfest 2022
  JavaScript(JS)/BMICalculator/index.css
  JavaScript(JS)/BMICalculator/index.html
  JavaScript(JS)/BMICalculator/index.js
Labels: hacktoberfest-accepted

#166 Create sum of elements.cpp
  CPP/sum of elements.cpp
Labels: hacktoberfest-accepted

#187 selection sort.cpp
  CPP/selection sort.cpp
  Python/pascal triangle.py
Labels: hacktoberfest-accepted

#190 binary search algorithm
  Python/binary_search.py
Labels: hacktoberfest-accepted

#189 quick sort algorithm using Js
  DSA Using JavaScripts/BubbleSort.js
  DSA Using JavaScripts/MergeSort.js
  DSA Using JavaScripts/QuickSort.js
  DSA Using JavaScripts/SelectionSort.js
Labels: hacktoberfest-accepted

#188 Craete heapSort.py
  Python/heapSort.py
Labels: hacktoberfest-accepted

#186 C++ Algos for ADT
  CONTRIBUTING.md
  CPP/Operations For ADTs/BinaryString.cpp
  CPP/Operations For ADTs/ReturnMinimumFromStack.cpp
  CPP/Operations For ADTs/ReverseDoubleList.cpp
  CPP/Operations For ADTs/SortQueues.cpp
  CPP/Operations For ADTs/SortedInsertLinkedList.cpp
  CPP/Operations For ADTs/SwapForDouleLinkedList.cpp
  CPP/Operations For ADTs/SwapForLinkedList.cpp
Labels: hacktoberfest-accepted

#185 added a responsive clock in Web-Dev Project
  CONTRIBUTING.md
  Web Development/Clock Using HTML, CSS & JS/clock.png
  Web Development/Clock Using HTML, CSS & JS/index.css
  Web Development/Clock Using HTML, CSS & JS/index.html
  Web Development/Clock Using HTML, CSS & JS/index.js
Labels: hacktoberfest-accepted

#183 RAJAT RAI PYTHON GUI GAMES UPDATE FILES
  CONTRIBUTING.md
  Python/Rajat Python GUI Files/CONTRIBUTING.md
  Python/Rajat Python GUI Files/QuizGame.py
  Python/Rajat Python GUI Files/SnakeGame.py
  Python/Rajat Python GUI Files/rpsGame.py
Labels: hacktoberfest-accepted

#182 Defanging an IP-LC
  CPP/Defanging an IP
Labels: hacktoberfest-accepted

#179 Create django.md
  Web Development/Documentation/django.md
Labels: hacktoberfest-accepted

#178 Group Anagrams
  Python/Group Anagrams.py
Labels: hacktoberfest-accepted

#171 add TWOMERCHANTS.cpp
  CPP/TWOMERCHANTS.cpp
Labels: hacktoberfest-accepted

#169 Added Weight Convertor GUI Python
  CONTRIBUTING.md
  Python/Weight Convertor GUI.py
Labels: hacktoberfest-accepted

#191 Tic_Tac_Toe
  Python/Tic_Tac_Toe.py
Labels: hacktoberfest-accepted

#192 Python Program to Copy Content of One File to Another
  Python/copy_file.py
Labels: hacktoberfest-accepted

#194 Added ArmstrongNumber Program code in Java folder and updated the Contributing.md section.
  CONTRIBUTING.md
  Java/ArmstsrongNumber.java
Labels: hacktoberfest-accepted

#195 Create Age_Calculator.py
  Python/Age_Calculator.py
Labels: hacktoberfest-accepted

#196 Create Alarm_Clock.py
  Alarm_Clock.py
Labels: hacktoberfest-accepted

#198 RSA Cryptography Program
  C/RSA.c
Labels: hacktoberfest-accepted

#199 adding drum-kit using JS
  JavaScript(JS)/Drum-Kit/README.md
  JavaScript(JS)/Drum-Kit/audio65.wav
  JavaScript(JS)/Drum-Kit/audio68.wav
  JavaScript(JS)/Drum-Kit/audio70.wav
  JavaScript(JS)/Drum-Kit/audio71.wav
  JavaScript(JS)/Drum-Kit/audio72.wav
  JavaScript(JS)/Drum-Kit/audio74.wav
  JavaScript(JS)/Drum-Kit/audio75.wav
  JavaScript(JS)/Drum-Kit/audio76.wav
  JavaScript(JS)/Drum-Kit/audio83.wav
  JavaScript(JS)/Drum-Kit/bg-img.webp
  JavaScript(JS)/Drum-Kit/drum.js
  JavaScript(JS)/Drum-Kit/index.html
  JavaScript(JS)/Drum-Kit/style.css
Labels: hacktoberfest-accepted

#201 Add files via upload
  Python/oddeve.py
Labels: hacktoberfest-accepted

#202 Audio to Text File in Python
  Python/AudioToText.py
Labels: hacktoberfest-accepted

#203 Added Sudoku Solver Program
  CONTRIBUTING.md
  Python/Sudoku-Solver.py
Labels: hacktoberfest-accepted

#204 Added an example of DecisionTreeClassifier algorithm
  CONTRIBUTING.md
  CPP/Threaded_BST.cpp
  CPP/Threaded_BST_Header.h
  Machine learning/Admission Predictor - Regression/Admission_Predict.csv
  Machine learning/Admission Predictor - Regression/Predictor.ipynb
Labels: hacktoberfest-accepted

#205 i want to contribute for the first time
  Java/pathSum2.java
Labels: hacktoberfest-accepted

#209 Hacktoberfest2022_aakash
  CONTRIBUTING.md
Labels: hacktoberfest-accepted
